[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

# decorations = "Buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"

dimensions = { columns = 100, lines = 35 }

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 15
